//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.10 at 12:54:00 PM CET 
//


package cnr.isti.sse.data.corrispettivi;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DatiRegistratoriTelematiciType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiRegistratoriTelematiciType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AliquotaIVA" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}RateType"/>
 *         &lt;element name="Natura" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}NaturaType" minOccurs="0"/>
 *         &lt;element name="Ammontare" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType"/>
 *         &lt;element name="Imposta" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType"/>
 *         &lt;element name="RifNormativo" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}String100LatinType" minOccurs="0"/>
 *         &lt;element name="VentilazioneIVA" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}VentilazioneIVAType" minOccurs="0"/>
 *         &lt;element name="TotaleAmmontareResi" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="TotaleAmmontareAnnulli" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiRegistratoriTelematiciType", propOrder = {
    "aliquotaIVA",
    "natura",
    "ammontare",
    "imposta",
    "rifNormativo",
    "ventilazioneIVA",
    "totaleAmmontareResi",
    "totaleAmmontareAnnulli"
})
public class DatiRegistratoriTelematiciType {

    @XmlElement(name = "AliquotaIVA", required = true)
    protected BigDecimal aliquotaIVA;
    @XmlElement(name = "Natura")
    protected NaturaType natura;
    @XmlElement(name = "Ammontare", required = true)
    protected BigDecimal ammontare;
    @XmlElement(name = "Imposta", required = true)
    protected BigDecimal imposta;
    @XmlElement(name = "RifNormativo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rifNormativo;
    @XmlElement(name = "VentilazioneIVA")
    protected VentilazioneIVAType ventilazioneIVA;
    @XmlElement(name = "TotaleAmmontareResi")
    protected BigDecimal totaleAmmontareResi;
    @XmlElement(name = "TotaleAmmontareAnnulli")
    protected BigDecimal totaleAmmontareAnnulli;

    /**
     * Gets the value of the aliquotaIVA property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaIVA() {
        return aliquotaIVA;
    }

    /**
     * Sets the value of the aliquotaIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaIVA(BigDecimal value) {
        this.aliquotaIVA = value;
    }

    /**
     * Gets the value of the natura property.
     * 
     * @return
     *     possible object is
     *     {@link NaturaType }
     *     
     */
    public NaturaType getNatura() {
        return natura;
    }

    /**
     * Sets the value of the natura property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturaType }
     *     
     */
    public void setNatura(NaturaType value) {
        this.natura = value;
    }

    /**
     * Gets the value of the ammontare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmmontare() {
        return ammontare;
    }

    /**
     * Sets the value of the ammontare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmmontare(BigDecimal value) {
        this.ammontare = value;
    }

    /**
     * Gets the value of the imposta property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImposta() {
        return imposta;
    }

    /**
     * Sets the value of the imposta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImposta(BigDecimal value) {
        this.imposta = value;
    }

    /**
     * Gets the value of the rifNormativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRifNormativo() {
        return rifNormativo;
    }

    /**
     * Sets the value of the rifNormativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRifNormativo(String value) {
        this.rifNormativo = value;
    }

    /**
     * Gets the value of the ventilazioneIVA property.
     * 
     * @return
     *     possible object is
     *     {@link VentilazioneIVAType }
     *     
     */
    public VentilazioneIVAType getVentilazioneIVA() {
        return ventilazioneIVA;
    }

    /**
     * Sets the value of the ventilazioneIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link VentilazioneIVAType }
     *     
     */
    public void setVentilazioneIVA(VentilazioneIVAType value) {
        this.ventilazioneIVA = value;
    }

    /**
     * Gets the value of the totaleAmmontareResi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaleAmmontareResi() {
        return totaleAmmontareResi;
    }

    /**
     * Sets the value of the totaleAmmontareResi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaleAmmontareResi(BigDecimal value) {
        this.totaleAmmontareResi = value;
    }

    /**
     * Gets the value of the totaleAmmontareAnnulli property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaleAmmontareAnnulli() {
        return totaleAmmontareAnnulli;
    }

    /**
     * Sets the value of the totaleAmmontareAnnulli property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaleAmmontareAnnulli(BigDecimal value) {
        this.totaleAmmontareAnnulli = value;
    }

}
